-- Secteurs commerciaux : la maille d'analyse des ventes n'est plus la ville mais le secteur
-- (AGADIR, BENI MELLAL, CASABLANCA-ELJADIDA, FES, GRAND SUD, MARRAKECH, MEKNES, ORIENTAL,
-- RABAT REGION, TANGER, TETOUAN). Le secteur est déduit de la ville du client et stocké sur la
-- fiche pour rester corrigeable à la main. La correspondance ville → secteur de référence vit
-- dans `src/lib/sectors.ts` ; ce script la reproduit pour reprendre l'existant.

ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "sector" text;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "clients_sector_idx" ON "clients" USING btree ("sector");--> statement-breakpoint

-- Reprise : clé de ville sans accent ni ponctuation, rapprochée de la table de correspondance.
WITH mapping(city_key, sector) AS (
  VALUES
    ('AGADIR','AGADIR'),('AIT MELLOUL','AGADIR'),('INEZGANE','AGADIR'),('TAROUDANT','AGADIR'),('TIZNIT','AGADIR'),('DCHEIRA','AGADIR'),('BIOUGRA','AGADIR'),('OULAD TEIMA','AGADIR'),
    ('BENI MELLAL','BENI MELLAL'),('KHOURIBGA','BENI MELLAL'),('FKIH BENSALEH','BENI MELLAL'),('FKIH BEN SALAH','BENI MELLAL'),('SOUK SEBT OULAD NEMMA','BENI MELLAL'),('SOUK SEBT','BENI MELLAL'),('BEJAAD','BENI MELLAL'),('OUED ZEM','BENI MELLAL'),('AZILAL','BENI MELLAL'),('KASBA TADLA','BENI MELLAL'),
    ('CASABLANCA','CASABLANCA-ELJADIDA'),('CASA','CASABLANCA-ELJADIDA'),('EL JADIDA','CASABLANCA-ELJADIDA'),('MOHAMMEDIA','CASABLANCA-ELJADIDA'),('SETTAT','CASABLANCA-ELJADIDA'),('BERRECHID','CASABLANCA-ELJADIDA'),('BOUSKOURA','CASABLANCA-ELJADIDA'),('HAD SOUALEM','CASABLANCA-ELJADIDA'),('DEROUA','CASABLANCA-ELJADIDA'),('BEN AHMED','CASABLANCA-ELJADIDA'),('BENSLIMANE','CASABLANCA-ELJADIDA'),('BOUZNIKA','CASABLANCA-ELJADIDA'),('OULED AZZOUZ','CASABLANCA-ELJADIDA'),('NOUACEUR','CASABLANCA-ELJADIDA'),('DAR BOUAZZA','CASABLANCA-ELJADIDA'),('AZEMMOUR','CASABLANCA-ELJADIDA'),('SIDI BENNOUR','CASABLANCA-ELJADIDA'),('MEDIOUNA','CASABLANCA-ELJADIDA'),
    ('FES','FES'),('SEFROU','FES'),('TAZA','FES'),('MOULAY YACOUB','FES'),
    ('LAAYOUNE','GRAND SUD'),('DAKHLA','GRAND SUD'),('TANTAN','GRAND SUD'),('TAN TAN','GRAND SUD'),('GUELMIM','GRAND SUD'),('OUARZAZATE','GRAND SUD'),('ERRACHIDIA','GRAND SUD'),('TATA','GRAND SUD'),('ZAGORA','GRAND SUD'),('SIDI IFNI','GRAND SUD'),('BOUJDOUR','GRAND SUD'),('ES SEMARA','GRAND SUD'),('SMARA','GRAND SUD'),('TINGHIR','GRAND SUD'),
    ('MARRAKECH','MARRAKECH'),('ESSAOUIRA','MARRAKECH'),('SAFI','MARRAKECH'),('KELAA SRAGHNA','MARRAKECH'),('EL KELAA DES SRAGHNA','MARRAKECH'),('BENGUERIR','MARRAKECH'),('BEN GUERIR','MARRAKECH'),('OURIKA','MARRAKECH'),('CHAMAIYA','MARRAKECH'),('YOUSSOUFIA','MARRAKECH'),('CHICHAOUA','MARRAKECH'),('AMIZMIZ','MARRAKECH'),('TAHANNAOUT','MARRAKECH'),
    ('MEKNES','MEKNES'),('AZROU','MEKNES'),('IFRANE','MEKNES'),('KHENIFRA','MEKNES'),('EL HAJEB','MEKNES'),('MIDELT','MEKNES'),
    ('OUJDA','ORIENTAL'),('BERKANE','ORIENTAL'),('NADOR','ORIENTAL'),('TAOURIRT','ORIENTAL'),('DRIOUCH','ORIENTAL'),('AL HOCEIMA','ORIENTAL'),('GUERCIF','ORIENTAL'),('JERADA','ORIENTAL'),('SAIDIA','ORIENTAL'),('ZAIO','ORIENTAL'),
    ('RABAT','RABAT REGION'),('SALE','RABAT REGION'),('KENITRA','RABAT REGION'),('TEMARA','RABAT REGION'),('AIN AOUDA','RABAT REGION'),('SKHIRAT','RABAT REGION'),('KHEMISSET','RABAT REGION'),('SIDI SLIMANE','RABAT REGION'),('SIDI KACEM','RABAT REGION'),('SOUK EL ARBAA','RABAT REGION'),('HARHOURA','RABAT REGION'),
    ('TANGER','TANGER'),('ASILAH','TANGER'),('LARACHE','TANGER'),('KSAR EL KEBIR','TANGER'),
    ('TETOUAN','TETOUAN'),('MDIQ','TETOUAN'),('M DIQ','TETOUAN'),('FNIDEQ','TETOUAN'),('MARTIL','TETOUAN'),('CHEFCHAOUEN','TETOUAN'),('OUAZZANE','TETOUAN')
),
keyed AS (
  SELECT id,
         trim(regexp_replace(translate(upper(city), 'ÀÁÂÄÃÉÈÊËÍÌÎÏÓÒÔÖÕÚÙÛÜÇÑ', 'AAAAAEEEEIIIIOOOOOUUUUCN'), '[^A-Z0-9]+', ' ', 'g')) AS city_key
  FROM clients
  WHERE sector IS NULL AND city IS NOT NULL AND city <> ''
)
UPDATE clients c SET sector = m.sector
FROM keyed k JOIN mapping m ON m.city_key = k.city_key
WHERE c.id = k.id;
