/**
 * Bibliothèque d'actions marketing COMANET — 30 modèles sur 5 leviers.
 *
 * Chaque modèle est une action complète : nom, concept, cibles, budget (min / idéal / max), structure de coûts par
 * poste (les postes d'activation sont ceux de `activation_cost_items`), modèle de portée (hypothèses affichées comme
 * telles), rétroplanning avec rôles, contenus nécessaires, KPI, conteneur d'exécution, non-répétition, saisonnalité.
 * Le moteur (`engine.ts`) l'adapte au produit, au budget disponible, à la ville, à la saison et aux données de la marque.
 * Ajouter un modèle = l'ajouter ici ; `tests/action-generator.test.ts` vérifie sa cohérence (parts = 1, postes valides…).
 */
import type { BudgetCategory } from "@/db/schema";
import type { ActionTemplate, AxisKey, ObjectiveKey, StepRole, TargetKey, TemplateLine, TemplateStep } from "./types";

/* ------------------------------ Référentiels ------------------------------ */

export const AXES: Record<AxisKey, { label: string; categories: BudgetCategory[]; mainCategory: BudgetCategory }> = {
  EVENEMENTIEL: { label: "Événementiel", categories: ["EVENEMENT", "SPONSORING", "CONGRES"], mainCategory: "EVENEMENT" },
  TRADE: { label: "Trade marketing", categories: ["TRADE", "PLV", "ANIMATION", "GOODIES", "ECHANTILLONS"], mainCategory: "TRADE" },
  DIGITAL: { label: "Digital", categories: ["META", "TIKTOK", "GOOGLE", "DIGITAL"], mainCategory: "META" },
  INFLUENCE: { label: "Influence", categories: ["INFLUENCE", "UGC"], mainCategory: "INFLUENCE" },
  CONTENU: { label: "Contenu", categories: ["CREATION", "SHOOTING", "AGENCE"], mainCategory: "CREATION" },
};
export const AXIS_KEYS = Object.keys(AXES) as AxisKey[];

export const OBJECTIVES: Record<ObjectiveKey, string> = {
  SELL_OUT: "Augmenter le sell-out",
  SELL_IN: "Augmenter le sell-in (commandes des pharmacies)",
  LANCEMENT: "Lancer un produit",
  NOTORIETE: "Développer la notoriété",
  ACQUISITION: "Recruter de nouvelles clientes",
  FIDELISATION: "Fidéliser / faire racheter",
  ECOULEMENT: "Écouler un stock",
};
export const OBJECTIVE_KEYS = Object.keys(OBJECTIVES) as ObjectiveKey[];

export const TARGETS: Record<TargetKey, string> = {
  FEMMES_25_45: "Femmes 25-45 ans",
  FEMMES_45_PLUS: "Femmes 45 ans et plus",
  JEUNES_18_25: "Jeunes 18-25 ans",
  HOMMES: "Hommes",
  MAMANS: "Mamans",
  SPORTIFS: "Sportifs / sportives",
  PHARMACIENS: "Pharmaciens et équipes comptoir",
  PRESCRIPTEURS: "Médecins prescripteurs",
};
export const TARGET_KEYS = Object.keys(TARGETS) as TargetKey[];

export const ROLE_LABELS: Record<StepRole, string> = { MARKETING: "Marketing", TRADE: "Trade / commercial", REGLEMENTAIRE: "Réglementaire", ANIMATRICE: "Animatrice", DIRECTION: "Direction" };

export const COMPLEXITY_LABELS = { LOW: "faible", MEDIUM: "moyenne", HIGH: "élevée" } as const;

/* ------------------------------ Aides de saisie ------------------------------ */

/** Postes d'activation (clé `activation_cost_items` → catégorie budgétaire du poste). */
const A = {
  lieu: (share: number, label = "Location du lieu"): TemplateLine => ({ label, category: "EVENEMENT", costItem: "LIEU", share }),
  traiteur: (share: number, label = "Traiteur / restauration"): TemplateLine => ({ label, category: "EVENEMENT", costItem: "TRAITEUR", share }),
  materiel: (share: number, label = "Matériel / stand"): TemplateLine => ({ label, category: "EVENEMENT", costItem: "MATERIEL", share }),
  impression: (share: number, label = "Branding / PLV imprimée"): TemplateLine => ({ label, category: "PLV", costItem: "IMPRESSION", share }),
  transport: (share: number, label = "Transport / logistique"): TemplateLine => ({ label, category: "AUTRES", costItem: "TRANSPORT", share }),
  cachet: (share: number, label = "Cachet intervenant"): TemplateLine => ({ label, category: "PRESCRIPTEURS", costItem: "CACHET", share }),
  echantillons: (share: number, label = "Sampling / échantillons"): TemplateLine => ({ label, category: "ECHANTILLONS", costItem: "ECHANTILLONS", share }),
  goodies: (share: number, label = "Goodies / cadeaux"): TemplateLine => ({ label, category: "GOODIES", costItem: "GOODIES", share }),
  hotesses: (share: number, label = "Animation / hôtesses"): TemplateLine => ({ label, category: "ANIMATION", costItem: "HOTESSES", share }),
  sponsoring: (share: number, label = "Emplacement / droits"): TemplateLine => ({ label, category: "SPONSORING", costItem: "SPONSORING", share }),
  communication: (share: number, label = "Création de contenu / relais"): TemplateLine => ({ label, category: "DIGITAL", costItem: "COMMUNICATION", share }),
  imprevus: (share = 0.08): TemplateLine => ({ label: "Imprévus", category: "AUTRES", costItem: "AUTRE", share }),
};

/** Postes de campagne (catégorie budgétaire seule). */
const C = (label: string, category: BudgetCategory, share: number): TemplateLine => ({ label, category, share });
const IMPREVUS = (share = 0.08): TemplateLine => ({ label: "Imprévus", category: "AUTRES", share });

const S = (offset: number, label: string, role: StepRole = "MARKETING"): TemplateStep => ({ offset, label, role });

const DERMO_ONLY: ActionTemplate["productKinds"] = ["DERMO", "SOLAIRE"];
const CLAIMS = "Messages et visuels : aucune allégation thérapeutique (cosmétique) ni promesse de guérison (complément) ; validation par le réglementaire avant diffusion.";

/* ------------------------------ Modèles ------------------------------ */

export const TEMPLATES: ActionTemplate[] = [
  /* ================================ ÉVÉNEMENTIEL ================================ */
  {
    key: "EVT_PADEL", axis: "EVENEMENTIEL", family: "Padel Challenge",
    name: (c) => `${c.hero} Padel Challenge`,
    concept: (c) => `Tournoi de padel amical de 2 heures dans un club de ${c.city ?? "la ville cible"} pour 32 à 48 joueuses. Stand ${c.brand} au bord des courts : test de ${c.product ?? "la gamme"}, sampling, coach pour l'échauffement, remise des prix en kit produit. Les inscriptions passent par Instagram et WhatsApp ; chaque participante repart avec la liste des pharmacies partenaires et une offre de bienvenue.`,
    objectives: { SELL_OUT: 0.9, NOTORIETE: 0.8, ACQUISITION: 0.85, LANCEMENT: 0.75, FIDELISATION: 0.5 },
    targets: ["FEMMES_25_45", "SPORTIFS", "JEUNES_18_25"], productKinds: "ANY",
    channels: ["Événement", "Instagram", "Micro-influence", "WhatsApp", "Pharmacies relais"],
    budget: { min: 9000, typical: 14800, max: 30000 },
    lines: [A.lieu(0.24, "Location des courts et du club"), A.impression(0.13, "Branding stand et courts"), A.echantillons(0.17), A.communication(0.12), A.goodies(0.13, "Goodies et dotations des gagnantes"), A.hotesses(0.07, "Coach et animation"), A.traiteur(0.06, "Rafraîchissements"), A.imprevus()],
    reach: { contactLabel: "participantes", costPerContact: 110, trialRate: 0.9, conversionRate: 0.25, unitsPerBuyer: 1 },
    steps: [S(-30, "Réserver le club et les courts"), S(-28, "Valider concept et budget", "DIRECTION"), S(-21, "Commander kits, goodies et branding"), S(-21, "Inviter 4 micro-influenceuses sportives"), S(-14, "Ouvrir les inscriptions (Instagram + WhatsApp)"), S(-10, "Prévenir 5 pharmacies du quartier : stock et offre", "TRADE"), S(-7, "Brief coach, hôtesses et kit sampling", "ANIMATRICE"), S(-1, "Installer stand et PLV", "ANIMATRICE"), S(0, "Tournoi : sampling, photos et vidéos"), S(1, "Publier l'aftermovie et remercier les participantes"), S(7, "Bilan : inscrites, essais, ventes des pharmacies relais")],
    contents: [{ format: "STORY", count: 3, title: "Ouverture des inscriptions", offset: -14 }, { format: "REEL", count: 1, title: "Teaser du tournoi", offset: -7 }, { format: "REEL", count: 1, title: "Aftermovie", offset: 1 }],
    extraKpis: [{ label: "Contenus d'influenceuses", value: () => 4 }],
    complexity: "MEDIUM", prepDays: 30, durationDays: 1, cooldownDays: 120,
    execution: { kind: "ACTIVATION", activationType: "EVENEMENT" },
    seasons: { "solaire-haute": 1, rentree: 1, ramadan: -1 }, cityBased: true, posBased: true, influencerBased: true,
  },
  {
    key: "EVT_BEAUTY_MORNING", axis: "EVENEMENTIEL", family: "Beauty Morning",
    name: (c) => `${c.hero} Beauty Morning`,
    concept: (c) => `Petit-déjeuner beauté de 25 à 40 invitées (clientes fidèles des pharmacies partenaires et pharmaciennes) dans un café de ${c.city ?? "la ville cible"}. Atelier routine de 45 minutes animé par une conseillère, test de ${c.product ?? "la gamme"} sur place, kit découverte et offre valable dans les pharmacies partenaires.`,
    objectives: { SELL_OUT: 0.8, FIDELISATION: 0.95, ACQUISITION: 0.6, LANCEMENT: 0.7, NOTORIETE: 0.5 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "MAMANS"], productKinds: "ANY",
    channels: ["Événement", "WhatsApp", "Pharmacies partenaires", "Instagram"],
    budget: { min: 5000, typical: 8500, max: 15000 },
    lines: [A.lieu(0.15, "Privatisation du café"), A.traiteur(0.22, "Petit-déjeuner"), A.echantillons(0.18, "Kits découverte"), A.goodies(0.14), A.impression(0.08, "Invitations et décoration"), A.communication(0.08, "Photos et vidéo"), A.hotesses(0.07, "Conseillère beauté"), A.imprevus()],
    reach: { contactLabel: "invitées", costPerContact: 250, trialRate: 1, conversionRate: 0.35, unitsPerBuyer: 1.2 },
    steps: [S(-21, "Réserver le lieu et le traiteur"), S(-18, "Constituer la liste d'invitées avec 3 pharmacies partenaires", "TRADE"), S(-14, "Envoyer les invitations WhatsApp personnalisées"), S(-7, "Préparer kits découverte et goodies"), S(-3, "Confirmer les présences"), S(-1, "Brief de la conseillère", "ANIMATRICE"), S(0, "Atelier routine et test produit"), S(1, "Remerciements et rappel de l'offre en pharmacie"), S(7, "Bilan : présence, ventes des pharmacies partenaires", "TRADE")],
    contents: [{ format: "STORY", count: 3, title: "Coulisses de l'atelier", offset: 0 }, { format: "POST", count: 1, title: "Retour en images", offset: 1 }],
    extraKpis: [{ label: "Taux de présence visé", value: () => "≥ 80 %" }],
    complexity: "LOW", prepDays: 21, durationDays: 1, cooldownDays: 60,
    execution: { kind: "ACTIVATION", activationType: "EVENEMENT" },
    seasons: { rentree: 1, ramadan: -1 }, cityBased: true, posBased: true, influencerBased: false,
  },
  {
    key: "EVT_MASTERCLASS", axis: "EVENEMENTIEL", family: "Masterclass",
    name: (c) => `Masterclass ${c.hero}`,
    concept: (c) => `Conférence-atelier de 60 à 80 personnes à ${c.city ?? "la ville cible"}, animée par un expert (dermatologue, nutritionniste ou pharmacienne) : comprendre les besoins, démonstration de ${c.product ?? "la gamme"}, questions-réponses, sampling à la sortie. Captation vidéo réutilisée en contenus pédagogiques.`,
    objectives: { NOTORIETE: 0.9, LANCEMENT: 0.9, SELL_OUT: 0.6, ACQUISITION: 0.7 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "PRESCRIPTEURS"], productKinds: "ANY",
    channels: ["Événement", "Expert", "Instagram", "Relations presse"],
    budget: { min: 12000, typical: 20000, max: 40000 },
    lines: [A.lieu(0.2, "Salle et technique"), A.cachet(0.18, "Cachet de l'expert"), A.traiteur(0.12, "Pause café"), A.echantillons(0.14), A.impression(0.08), A.communication(0.12, "Captation vidéo et relais"), A.goodies(0.08), A.imprevus()],
    reach: { contactLabel: "participants", costPerContact: 270, trialRate: 0.85, conversionRate: 0.22, unitsPerBuyer: 1 },
    steps: [S(-35, "Recruter l'expert et fixer le thème"), S(-30, "Valider concept et budget", "DIRECTION"), S(-28, "Réserver la salle et la captation"), S(-21, "Ouvrir les inscriptions"), S(-14, "Valider le support de l'expert", "REGLEMENTAIRE"), S(-10, "Inviter pharmaciens et presse", "TRADE"), S(-3, "Préparer sampling et PLV"), S(0, "Masterclass, captation et sampling"), S(3, "Monter 3 extraits vidéo"), S(10, "Bilan : participants, contacts, ventes relais")],
    contents: [{ format: "POST", count: 1, title: "Annonce de la masterclass", offset: -21 }, { format: "REEL", count: 3, title: "Extraits de la masterclass", offset: 3 }],
    extraKpis: [{ label: "Extraits vidéo réutilisables", value: () => 3 }],
    complexity: "HIGH", prepDays: 35, durationDays: 1, cooldownDays: 150,
    execution: { kind: "ACTIVATION", activationType: "EVENEMENT" },
    seasons: { rentree: 1, ramadan: -1 }, cityBased: true, posBased: false, influencerBased: false, compliance: CLAIMS,
  },
  {
    key: "EVT_WORKSHOP", axis: "EVENEMENTIEL", family: "Atelier routine",
    name: (c) => `Atelier routine ${c.hero}`,
    concept: (c) => `Atelier de 12 à 15 personnes dans une pharmacie partenaire de ${c.city ?? "la ville cible"} : diagnostic de peau, construction de la routine, application de ${c.product ?? "la gamme"} par une conseillère, kit routine offert et offre le jour même au comptoir.`,
    objectives: { SELL_OUT: 0.95, FIDELISATION: 0.8, ACQUISITION: 0.6, LANCEMENT: 0.6 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "JEUNES_18_25"], productKinds: DERMO_ONLY,
    channels: ["Pharmacie partenaire", "WhatsApp", "Instagram"],
    budget: { min: 3000, typical: 5500, max: 9000 },
    lines: [A.lieu(0.12, "Mise à disposition / aménagement"), A.echantillons(0.25, "Kits routine"), A.goodies(0.18), A.hotesses(0.2, "Conseillère beauté"), A.impression(0.09, "Affiches et invitations"), A.communication(0.08), A.imprevus()],
    reach: { contactLabel: "participantes", costPerContact: 300, trialRate: 1, conversionRate: 0.45, unitsPerBuyer: 1.3 },
    steps: [S(-14, "Choisir la pharmacie hôte et fixer la date", "TRADE"), S(-12, "Commander kits et goodies"), S(-10, "Inviter les clientes via la pharmacie et WhatsApp"), S(-5, "Vérifier le stock de la pharmacie", "TRADE"), S(-1, "Brief de la conseillère", "ANIMATRICE"), S(0, "Atelier et ventes au comptoir", "ANIMATRICE"), S(7, "Bilan : participantes, ventes de la pharmacie", "TRADE")],
    contents: [{ format: "STORY", count: 3, title: "Atelier en pharmacie", offset: 0 }],
    extraKpis: [{ label: "Ventes le jour même", value: () => "≥ 40 % des participantes" }],
    complexity: "LOW", prepDays: 14, durationDays: 1, cooldownDays: 45,
    execution: { kind: "ACTIVATION", activationType: "OPERATION_PHARMACIE" },
    seasons: { ramadan: -1 }, cityBased: true, posBased: true, influencerBased: false,
  },
  {
    key: "EVT_POPUP", axis: "EVENEMENTIEL", family: "Pop-up",
    name: (c) => `${c.hero} Pop-up`,
    concept: (c) => `Stand éphémère de 2 jours dans un centre commercial de ${c.city ?? "la ville cible"} : diagnostic express, test de ${c.product ?? "la gamme"}, jeu concours et carte des pharmacies partenaires (QR code) pour acheter près de chez soi.`,
    objectives: { NOTORIETE: 0.9, ACQUISITION: 0.9, SELL_OUT: 0.7, LANCEMENT: 0.85 },
    targets: ["FEMMES_25_45", "JEUNES_18_25", "MAMANS", "FEMMES_45_PLUS"], productKinds: "ANY",
    channels: ["Centre commercial", "Instagram", "QR code pharmacies", "Jeu concours"],
    budget: { min: 15000, typical: 25000, max: 50000 },
    lines: [A.sponsoring(0.3, "Emplacement en galerie"), A.materiel(0.15, "Stand"), A.hotesses(0.15, "Hôtesses (2 jours)"), A.echantillons(0.14), A.impression(0.06), A.communication(0.07), A.goodies(0.05, "Lots du jeu concours"), A.imprevus()],
    reach: { contactLabel: "visiteurs au stand", costPerContact: 60, trialRate: 0.5, conversionRate: 0.15, unitsPerBuyer: 1 },
    steps: [S(-40, "Négocier l'emplacement en galerie"), S(-35, "Valider concept et budget", "DIRECTION"), S(-28, "Commander le stand et le branding"), S(-21, "Recruter et former les hôtesses", "ANIMATRICE"), S(-14, "Lister les pharmacies partenaires à proximité (QR code)", "TRADE"), S(-7, "Annonce sur Instagram"), S(-1, "Montage du stand"), S(0, "Ouverture du pop-up (jour 1)", "ANIMATRICE"), S(1, "Jour 2 et démontage", "ANIMATRICE"), S(10, "Bilan : visiteurs, essais, scans, ventes relais")],
    contents: [{ format: "REEL", count: 1, title: "Pop-up : venez nous voir", offset: -5 }, { format: "STORY", count: 6, title: "Live du stand", offset: 0 }],
    extraKpis: [{ label: "Scans du QR code pharmacies", value: (b) => Math.round(b / 60 * 0.2) }],
    complexity: "HIGH", prepDays: 40, durationDays: 2, cooldownDays: 180,
    execution: { kind: "ACTIVATION", activationType: "EVENEMENT" },
    seasons: { ramadan: 1, rentree: 1 }, cityBased: true, posBased: true, influencerBased: false,
  },
  {
    key: "EVT_VIP", axis: "EVENEMENTIEL", family: "Soirée VIP",
    name: (c) => `Soirée VIP ${c.brand}`,
    concept: (c) => `Soirée privée pour 30 à 50 meilleures clientes (fichiers des pharmacies partenaires et abonnées les plus engagées) à ${c.city ?? "la ville cible"} : mise en avant de ${c.product ?? "la gamme"}, coffret cadeau, photo booth, offre exclusive en pharmacie valable 15 jours.`,
    objectives: { FIDELISATION: 1, SELL_OUT: 0.6, NOTORIETE: 0.6, LANCEMENT: 0.6 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS"], productKinds: "ANY",
    channels: ["Événement privé", "WhatsApp", "Pharmacies partenaires", "Instagram"],
    budget: { min: 12000, typical: 18000, max: 35000 },
    lines: [A.lieu(0.2), A.traiteur(0.22, "Cocktail / ftour"), A.goodies(0.18, "Coffrets cadeaux"), A.echantillons(0.08), A.materiel(0.08, "Photo booth et décoration"), A.communication(0.08), A.impression(0.08, "Invitations"), A.imprevus()],
    reach: { contactLabel: "invitées", costPerContact: 450, trialRate: 1, conversionRate: 0.5, unitsPerBuyer: 1.5 },
    steps: [S(-30, "Réserver le lieu et le traiteur"), S(-28, "Valider la liste et le budget", "DIRECTION"), S(-21, "Sélectionner les invitées avec les pharmacies partenaires", "TRADE"), S(-18, "Commander coffrets et décoration"), S(-14, "Envoyer les invitations"), S(-3, "Confirmer les présences"), S(0, "Soirée VIP"), S(1, "Remerciements et rappel de l'offre"), S(15, "Bilan : ventes de l'offre exclusive", "TRADE")],
    contents: [{ format: "STORY", count: 4, title: "Soirée VIP", offset: 0 }, { format: "POST", count: 1, title: "Retour en images", offset: 1 }],
    extraKpis: [{ label: "Offre exclusive utilisée", value: () => "≥ 50 % des invitées" }],
    complexity: "MEDIUM", prepDays: 30, durationDays: 1, cooldownDays: 180,
    execution: { kind: "ACTIVATION", activationType: "EVENEMENT" },
    seasons: { ramadan: 1 }, cityBased: true, posBased: true, influencerBased: false,
  },
  {
    key: "EVT_PRESCRIBERS", axis: "EVENEMENTIEL", family: "Rencontre prescripteurs",
    name: (c) => `Rencontre prescripteurs ${c.hero}`,
    concept: (c) => `Dîner-débat pour 15 à 25 médecins (dermatologues, pédiatres, généralistes) de ${c.city ?? "la ville cible"} : présentation des données de ${c.product ?? "la gamme"} par un expert, échanges cas pratiques, remise d'échantillons pour les patients et du dossier produit.`,
    objectives: { LANCEMENT: 0.9, ACQUISITION: 0.8, NOTORIETE: 0.7, SELL_OUT: 0.6, SELL_IN: 0.5 },
    targets: ["PRESCRIPTEURS"], productKinds: "ANY",
    channels: ["Événement médical", "Délégation médicale", "Échantillons patients"],
    budget: { min: 15000, typical: 25000, max: 45000 },
    lines: [A.lieu(0.1), A.traiteur(0.3, "Dîner"), A.cachet(0.22, "Cachet de l'expert"), A.echantillons(0.15, "Échantillons patients"), A.impression(0.07, "Dossier produit"), A.goodies(0.08), A.imprevus()],
    reach: { contactLabel: "médecins", costPerContact: 1100, trialRate: 1, conversionRate: 0.6, unitsPerBuyer: 8 },
    steps: [S(-35, "Recruter l'expert et fixer le programme"), S(-30, "Valider budget et conformité", "DIRECTION"), S(-28, "Lister les médecins cibles avec la délégation médicale"), S(-21, "Envoyer les invitations"), S(-14, "Valider la présentation et le dossier", "REGLEMENTAIRE"), S(-7, "Préparer échantillons et dossiers"), S(0, "Dîner-débat"), S(3, "Planifier les visites de suivi des médecins présents"), S(30, "Bilan : visites, ordonnances, ventes de la zone")],
    contents: [],
    extraKpis: [{ label: "Visites de suivi planifiées", value: (b) => Math.round(b / 1100) }],
    complexity: "HIGH", prepDays: 35, durationDays: 1, cooldownDays: 120,
    execution: { kind: "ACTIVATION", activationType: "EVENEMENT" },
    seasons: { ramadan: -1, rentree: 1 }, cityBased: true, posBased: false, influencerBased: false, compliance: CLAIMS,
  },
  {
    key: "EVT_SAMPLING_TOUR", axis: "EVENEMENTIEL", family: "Sampling Tour",
    name: (c) => `${c.hero} Sampling Tour`,
    concept: (c) => `Tournée de sampling de 3 jours à ${c.city ?? "la ville cible"} (salles de sport, universités, centres commerciaux) : 1 000 à 2 000 échantillons de ${c.product ?? "la gamme"} remis avec une carte QR code vers les pharmacies partenaires et une offre de premier achat.`,
    objectives: { ACQUISITION: 0.9, LANCEMENT: 0.9, NOTORIETE: 0.8, SELL_OUT: 0.7 },
    targets: ["JEUNES_18_25", "FEMMES_25_45", "SPORTIFS", "HOMMES"], productKinds: "ANY",
    channels: ["Street sampling", "QR code pharmacies", "Instagram"],
    budget: { min: 7000, typical: 12000, max: 25000 },
    lines: [A.echantillons(0.38, "Échantillons"), A.hotesses(0.24, "Équipe de sampling (3 jours)"), A.transport(0.08), A.impression(0.1, "Cartes et kakémonos"), A.communication(0.07), A.goodies(0.05), A.imprevus()],
    reach: { contactLabel: "personnes échantillonnées", costPerContact: 9, trialRate: 0.7, conversionRate: 0.04, unitsPerBuyer: 1 },
    steps: [S(-21, "Obtenir les autorisations (salles, campus, galeries)"), S(-18, "Commander échantillons et cartes"), S(-14, "Recruter l'équipe de sampling", "ANIMATRICE"), S(-7, "Informer les pharmacies de la zone", "TRADE"), S(0, "Jour 1 de la tournée", "ANIMATRICE"), S(2, "Jour 3 et retour du matériel", "ANIMATRICE"), S(14, "Bilan : échantillons remis, scans, ventes relais")],
    contents: [{ format: "STORY", count: 4, title: "Où nous trouver", offset: 0 }],
    extraKpis: [{ label: "Échantillons remis", value: (b) => Math.round(b / 9) }],
    complexity: "MEDIUM", prepDays: 21, durationDays: 3, cooldownDays: 90,
    execution: { kind: "ACTIVATION", activationType: "SAMPLING" },
    seasons: { rentree: 1, "solaire-haute": 1 }, cityBased: true, posBased: true, influencerBased: false,
  },

  /* ================================ TRADE ================================ */
  {
    key: "TR_SELLOUT_CHALLENGE", axis: "TRADE", family: "Sell-out Challenge",
    name: (c) => `${c.hero} Sell-out Challenge`,
    concept: (c) => `Challenge de 4 semaines pour 10 à 15 pharmacies partenaires : objectif d'unités de ${c.product ?? "la gamme"} vendues par officine, dotation des équipes comptoir des 3 meilleures, kit vitrine et échantillons pour faire essayer. Classement partagé chaque semaine par WhatsApp.`,
    objectives: { SELL_OUT: 1, ECOULEMENT: 0.9, SELL_IN: 0.7 },
    targets: ["PHARMACIENS"], productKinds: "ANY",
    channels: ["Pharmacies partenaires", "Équipes comptoir", "WhatsApp"],
    budget: { min: 6000, typical: 12000, max: 25000 },
    lines: [A.goodies(0.3, "Dotations des équipes gagnantes"), A.impression(0.18, "Kit vitrine"), A.echantillons(0.2), A.hotesses(0.12, "Visites de lancement"), A.communication(0.06), A.transport(0.06), A.imprevus()],
    reach: { contactLabel: "clientes conseillées en officine", costPerContact: 25, trialRate: 0.35, conversionRate: 0.5, unitsPerBuyer: 1 },
    steps: [S(-14, "Sélectionner 10 à 15 pharmacies (passage, stock)", "TRADE"), S(-12, "Valider règlement et dotations", "DIRECTION"), S(-10, "Produire kits vitrine et classement"), S(-7, "Visites de lancement et vérification du stock", "TRADE"), S(0, "Lancement du challenge", "TRADE"), S(7, "Classement semaine 1 (WhatsApp)", "TRADE"), S(14, "Classement semaine 2", "TRADE"), S(21, "Classement semaine 3", "TRADE"), S(28, "Clôture, remise des dotations, bilan sell-out", "TRADE")],
    contents: [{ format: "VISUEL_PHARMACIE", count: 1, title: "Visuel du challenge", offset: -10 }],
    extraKpis: [{ label: "Pharmacies participantes", value: () => "10 à 15" }],
    complexity: "MEDIUM", prepDays: 14, durationDays: 28, cooldownDays: 90,
    execution: { kind: "ACTIVATION", activationType: "OPERATION_PHARMACIE" },
    seasons: { ramadan: 1 }, cityBased: false, posBased: true, influencerBased: false,
  },
  {
    key: "TR_POS_DAYS", axis: "TRADE", family: "Journées en pharmacie",
    name: (c) => `Journées ${c.hero} en pharmacie`,
    concept: (c) => `Deux journées d'animation par officine dans 6 à 8 pharmacies à fort passage : animatrice formée sur ${c.product ?? "la gamme"}, test, conseil et offre du jour. Les pharmacies sont choisies parmi les meilleurs clients et ceux dont les ventes reculent.`,
    objectives: { SELL_OUT: 1, ECOULEMENT: 0.85, LANCEMENT: 0.7, ACQUISITION: 0.6 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "MAMANS", "PHARMACIENS"], productKinds: "ANY",
    channels: ["Animation en pharmacie", "Conseil comptoir"],
    budget: { min: 5000, typical: 9000, max: 20000 },
    lines: [A.hotesses(0.4, "Animatrices (journées)"), A.echantillons(0.22), A.impression(0.12, "PLV d'animation"), A.goodies(0.12), A.transport(0.06), A.imprevus()],
    reach: { contactLabel: "clientes abordées", costPerContact: 30, trialRate: 0.6, conversionRate: 0.35, unitsPerBuyer: 1 },
    steps: [S(-10, "Planifier les journées avec les pharmacies", "TRADE"), S(-7, "Vérifier les stocks et passer les commandes", "TRADE"), S(-5, "Former les animatrices sur le produit", "ANIMATRICE"), S(-2, "Préparer échantillons et PLV"), S(0, "Première journée d'animation", "ANIMATRICE"), S(13, "Dernière journée d'animation", "ANIMATRICE"), S(14, "Saisie des ventes et relevés de stock (saisie terrain)", "ANIMATRICE"), S(21, "Bilan : sell-out par pharmacie", "TRADE")],
    contents: [],
    extraKpis: [{ label: "Journées d'animation", value: () => "12 à 16" }],
    complexity: "LOW", prepDays: 10, durationDays: 14, cooldownDays: 60,
    execution: { kind: "ACTIVATION", activationType: "OPERATION_PHARMACIE" },
    seasons: { ramadan: 1, rentree: 1 }, cityBased: false, posBased: true, influencerBased: false,
  },
  {
    key: "TR_BUNDLE", axis: "TRADE", family: "Bundle / pack",
    name: (c) => `Pack ${c.hero} Duo`,
    concept: (c) => `Offre pack de 6 semaines dans les pharmacies partenaires : ${c.product ?? "le produit"} + un mini-format (ou deux unités à prix avantageux), signalé par un stop-rayon et un sticker. Idéal pour écouler un stock et augmenter le panier.`,
    objectives: { ECOULEMENT: 1, SELL_OUT: 0.8, SELL_IN: 0.8, FIDELISATION: 0.6 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "MAMANS", "PHARMACIENS"], productKinds: "ANY",
    channels: ["Pharmacies partenaires", "PLV", "WhatsApp"],
    budget: { min: 4000, typical: 8000, max: 18000 },
    lines: [A.echantillons(0.3, "Mini-formats offerts"), A.impression(0.25, "Stop-rayons et stickers"), A.goodies(0.1), A.communication(0.12), A.transport(0.07), A.hotesses(0.08, "Mise en place"), A.imprevus()],
    reach: { contactLabel: "clientes exposées à l'offre", costPerContact: 20, trialRate: 0.5, conversionRate: 0.5, unitsPerBuyer: 2 },
    steps: [S(-14, "Définir l'offre et le prix conseillé", "TRADE"), S(-12, "Valider l'offre (marge, politique tarifaire)", "DIRECTION"), S(-10, "Produire stickers et stop-rayons"), S(-7, "Préparer les packs et les livrer", "TRADE"), S(0, "Lancement de l'offre", "TRADE"), S(21, "Point mi-parcours : stock des packs", "TRADE"), S(42, "Bilan : packs vendus, stock restant", "TRADE")],
    contents: [{ format: "VISUEL_PHARMACIE", count: 1, title: "Visuel de l'offre pack", offset: -10 }, { format: "STORY", count: 2, title: "L'offre pack en pharmacie", offset: 0 }],
    extraKpis: [{ label: "Packs vendus", value: (b) => Math.round(b / 20 * 0.25) }],
    complexity: "LOW", prepDays: 14, durationDays: 42, cooldownDays: 90,
    execution: { kind: "ACTIVATION", activationType: "OPERATION_PHARMACIE" },
    seasons: { ramadan: 1, rentree: 1 }, cityBased: false, posBased: true, influencerBased: false,
    compliance: "Prix et remise : respecter la politique tarifaire (prix public conseillé) et la marge des pharmacies.",
  },
  {
    key: "TR_GWP", axis: "TRADE", family: "Gift With Purchase",
    name: (c) => `${c.hero} : un cadeau pour l'achat`,
    concept: (c) => `Pendant 4 semaines, pour l'achat de ${c.product ?? "un produit de la gamme"} dans les pharmacies partenaires, une trousse ou un mini-format offert (stock limité). Annonce en vitrine, sur Instagram et par WhatsApp.`,
    objectives: { SELL_OUT: 0.9, ECOULEMENT: 0.8, FIDELISATION: 0.75, ACQUISITION: 0.6 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "MAMANS", "JEUNES_18_25"], productKinds: "ANY",
    channels: ["Pharmacies partenaires", "Instagram", "WhatsApp"],
    budget: { min: 5000, typical: 10000, max: 22000 },
    lines: [A.goodies(0.45, "Cadeaux (trousses / mini-formats)"), A.impression(0.15), A.communication(0.12), A.transport(0.07), A.hotesses(0.13, "Mise en place en officine"), A.imprevus()],
    reach: { contactLabel: "clientes exposées à l'offre", costPerContact: 35, trialRate: 0.7, conversionRate: 0.6, unitsPerBuyer: 1 },
    steps: [S(-21, "Choisir et commander les cadeaux"), S(-14, "Répartir les cadeaux par pharmacie", "TRADE"), S(-10, "Produire la PLV de l'offre"), S(-5, "Livrer cadeaux et PLV", "TRADE"), S(0, "Lancement de l'offre"), S(14, "Réassort des cadeaux si besoin", "TRADE"), S(28, "Bilan : cadeaux remis, ventes", "TRADE")],
    contents: [{ format: "POST", count: 1, title: "Annonce de l'offre", offset: 0 }, { format: "STORY", count: 3, title: "Rappel de l'offre", offset: 14 }],
    extraKpis: [{ label: "Cadeaux remis", value: (b) => Math.round((b * 0.45) / 25) }],
    complexity: "LOW", prepDays: 21, durationDays: 28, cooldownDays: 90,
    execution: { kind: "ACTIVATION", activationType: "GOODIES" },
    seasons: { ramadan: 1 }, cityBased: false, posBased: true, influencerBased: false,
  },
  {
    key: "TR_RETAILER_INCENTIVE", axis: "TRADE", family: "Retailer Incentive",
    name: (c) => `Club pharmaciens ${c.brand}`,
    concept: (c) => `Programme de 2 mois pour les équipes comptoir : formation produit de 30 minutes sur ${c.product ?? "la gamme"}, quiz, dotation par palier de commandes. Objectif : référencement et recommandation active au comptoir.`,
    objectives: { SELL_IN: 1, SELL_OUT: 0.7, LANCEMENT: 0.75 },
    targets: ["PHARMACIENS"], productKinds: "ANY",
    channels: ["Visites commerciales", "Formation comptoir", "WhatsApp"],
    budget: { min: 6000, typical: 12000, max: 30000 },
    lines: [A.goodies(0.35, "Dotations par palier"), A.cachet(0.15, "Formatrice"), A.impression(0.12, "Support de formation"), A.transport(0.1), A.communication(0.1), A.traiteur(0.1, "Petits-déjeuners de formation"), A.imprevus()],
    reach: { contactLabel: "officines", costPerContact: 800, trialRate: 1, conversionRate: 0.7, unitsPerBuyer: 12 },
    steps: [S(-21, "Définir les paliers et les dotations", "TRADE"), S(-18, "Valider le programme", "DIRECTION"), S(-14, "Préparer le support de formation", "MARKETING"), S(-10, "Valider le support", "REGLEMENTAIRE"), S(0, "Lancement : visites et formations", "TRADE"), S(30, "Point des paliers à mi-parcours", "TRADE"), S(60, "Remise des dotations et bilan sell-in", "TRADE")],
    contents: [],
    extraKpis: [{ label: "Équipes formées", value: (b) => Math.round(b / 800) }],
    complexity: "MEDIUM", prepDays: 21, durationDays: 60, cooldownDays: 120,
    execution: { kind: "ACTIVATION", activationType: "OPERATION_PHARMACIE" },
    seasons: { rentree: 1 }, cityBased: false, posBased: true, influencerBased: false,
    compliance: "Dotations : conformes aux règles d'avantages aux professionnels de santé.",
  },
  {
    key: "TR_MERCH", axis: "TRADE", family: "Merchandising",
    name: (c) => `Vitrine ${c.hero}`,
    concept: (c) => `Mise en avant de 6 semaines dans 10 à 15 officines : vitrine, présentoir comptoir et stop-rayon ${c.product ?? "de la gamme"}, posés et photographiés. Les pharmacies sont choisies pour leur passage et leur potentiel.`,
    objectives: { SELL_OUT: 0.8, LANCEMENT: 0.85, NOTORIETE: 0.7, ECOULEMENT: 0.6 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "MAMANS", "JEUNES_18_25", "HOMMES"], productKinds: "ANY",
    channels: ["Vitrine", "PLV comptoir", "Stop-rayon"],
    budget: { min: 5000, typical: 10000, max: 25000 },
    lines: [A.impression(0.45, "Vitrines et stop-rayons"), A.materiel(0.15, "Présentoirs"), A.hotesses(0.15, "Pose et relevé photo"), A.transport(0.1), A.goodies(0.07), A.imprevus()],
    reach: { contactLabel: "clientes exposées", costPerContact: 15, trialRate: 0.1, conversionRate: 0.5, unitsPerBuyer: 1 },
    steps: [S(-21, "Sélectionner les officines et obtenir l'accord", "TRADE"), S(-18, "Créer les visuels"), S(-14, "Valider les visuels", "REGLEMENTAIRE"), S(-10, "Imprimer et livrer"), S(0, "Pose en officine et photos", "ANIMATRICE"), S(21, "Contrôle de la mise en avant", "TRADE"), S(42, "Retrait et bilan sell-out", "TRADE")],
    contents: [{ format: "VISUEL_PHARMACIE", count: 2, title: "Visuels vitrine et stop-rayon", offset: -18 }],
    extraKpis: [{ label: "Vitrines posées", value: () => "10 à 15" }],
    complexity: "LOW", prepDays: 21, durationDays: 42, cooldownDays: 120,
    execution: { kind: "ACTIVATION", activationType: "PLV" },
    seasons: { "solaire-haute": 1, ramadan: 1 }, cityBased: false, posBased: true, influencerBased: false,
  },
  {
    key: "TR_SAMPLING_WEEK", axis: "TRADE", family: "Sampling Week",
    name: (c) => `Semaine découverte ${c.hero}`,
    concept: (c) => `Une semaine dans 8 à 12 pharmacies : l'équipe comptoir remet un échantillon de ${c.product ?? "la gamme"} à chaque cliente concernée, avec une carte offre de premier achat. Suivi des ventes à 30 jours.`,
    objectives: { ACQUISITION: 0.9, LANCEMENT: 0.9, SELL_OUT: 0.8 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "MAMANS", "JEUNES_18_25", "HOMMES", "PHARMACIENS"], productKinds: "ANY",
    channels: ["Pharmacies partenaires", "Conseil comptoir"],
    budget: { min: 4000, typical: 7500, max: 15000 },
    lines: [A.echantillons(0.5), A.impression(0.15, "Cartes offre"), A.transport(0.1), A.hotesses(0.1, "Brief des équipes"), A.goodies(0.07), A.imprevus()],
    reach: { contactLabel: "clientes échantillonnées", costPerContact: 8, trialRate: 0.9, conversionRate: 0.06, unitsPerBuyer: 1 },
    steps: [S(-14, "Choisir les pharmacies et les quantités", "TRADE"), S(-10, "Commander échantillons et cartes"), S(-5, "Livrer et briefer les équipes comptoir", "TRADE"), S(0, "Début de la semaine découverte", "TRADE"), S(7, "Fin de la semaine : quantités remises", "TRADE"), S(30, "Bilan : ventes à 30 jours par pharmacie", "TRADE")],
    contents: [],
    extraKpis: [{ label: "Échantillons remis", value: (b) => Math.round((b * 0.5) / 4) }],
    complexity: "LOW", prepDays: 14, durationDays: 7, cooldownDays: 75,
    execution: { kind: "ACTIVATION", activationType: "SAMPLING" },
    seasons: {}, cityBased: false, posBased: true, influencerBased: false,
  },

  /* ================================ DIGITAL ================================ */
  {
    key: "DG_UGC", axis: "DIGITAL", family: "Campagne UGC",
    name: (c) => `${c.hero} UGC Wave`,
    concept: (c) => `8 à 12 vidéos UGC de vraies utilisatrices de ${c.product ?? "la gamme"} (routine, avis, résultat cosmétique), diffusées en publicité Meta pendant 3 semaines vers ${c.target.toLowerCase()} ; objectif conversation WhatsApp ou recherche de la pharmacie la plus proche.`,
    objectives: { ACQUISITION: 0.9, SELL_OUT: 0.8, LANCEMENT: 0.75, NOTORIETE: 0.6 },
    targets: ["FEMMES_25_45", "JEUNES_18_25", "MAMANS", "FEMMES_45_PLUS"], productKinds: "ANY",
    channels: ["Meta Ads", "UGC", "WhatsApp", "Pharmacies relais"],
    budget: { min: 6000, typical: 12000, max: 30000 },
    lines: [C("Production UGC", "UGC", 0.35), C("Diffusion Meta", "META", 0.5), C("Montage et déclinaisons", "CREATION", 0.07), IMPREVUS()],
    reach: { contactLabel: "conversations / clics qualifiés", costPerContact: 12, trialRate: 0.3, conversionRate: 0.35, unitsPerBuyer: 1, usesAdsCost: true },
    steps: [S(-21, "Brief UGC et sélection des créatrices"), S(-14, "Réception et tri des vidéos"), S(-10, "Valider les messages", "REGLEMENTAIRE"), S(-7, "Paramétrer la campagne Meta (audiences, budget)"), S(-3, "Informer les pharmacies relais (stock, argumentaire)", "TRADE"), S(0, "Lancement de la diffusion"), S(7, "Optimisation : couper les vidéos sous la moyenne"), S(21, "Bilan : coût par résultat, ventes des pharmacies relais")],
    contents: [{ format: "UGC", count: 10, title: "Vidéos UGC", offset: -14 }],
    extraKpis: [{ label: "Vidéos UGC exploitables", value: () => "8 à 12" }],
    complexity: "MEDIUM", prepDays: 21, durationDays: 21, cooldownDays: 60,
    execution: { kind: "CAMPAIGN", campaignType: "ACQUISITION", channel: "META" },
    seasons: {}, cityBased: false, posBased: true, influencerBased: false, compliance: CLAIMS,
  },
  {
    key: "DG_CONVERSION", axis: "DIGITAL", family: "Campagne de conversion",
    name: (c) => `${c.hero} Conversion Sprint`,
    concept: () => `Campagne Meta de 3 semaines orientée conversations et visites vers la liste des pharmacies partenaires : 3 créations (bénéfice, preuve, offre) testées en A/B, budget concentré sur la meilleure à J+7.`,
    objectives: { SELL_OUT: 1, ACQUISITION: 0.8, ECOULEMENT: 0.7 },
    targets: ["FEMMES_25_45", "JEUNES_18_25", "MAMANS", "FEMMES_45_PLUS", "HOMMES", "SPORTIFS"], productKinds: "ANY",
    channels: ["Meta Ads", "WhatsApp", "Pharmacies relais"],
    budget: { min: 5000, typical: 10000, max: 40000 },
    lines: [C("Diffusion Meta", "META", 0.78), C("Créations (3 versions)", "CREATION", 0.14), IMPREVUS()],
    reach: { contactLabel: "conversations / clics qualifiés", costPerContact: 10, trialRate: 0.3, conversionRate: 0.3, unitsPerBuyer: 1, usesAdsCost: true },
    steps: [S(-10, "Brief des 3 créations"), S(-7, "Valider les créations", "REGLEMENTAIRE"), S(-5, "Paramétrer la campagne et le suivi WhatsApp"), S(-3, "Vérifier le stock des pharmacies relais", "TRADE"), S(0, "Lancement"), S(7, "Garder la meilleure création, couper les autres"), S(21, "Bilan : coût par résultat, ventes relais")],
    contents: [{ format: "REEL", count: 2, title: "Créations bénéfice et preuve", offset: -5 }, { format: "POST", count: 1, title: "Création offre", offset: -5 }],
    extraKpis: [],
    complexity: "LOW", prepDays: 10, durationDays: 21, cooldownDays: 45,
    execution: { kind: "CAMPAIGN", campaignType: "CONVERSION", channel: "META" },
    seasons: { ramadan: 1 }, cityBased: false, posBased: true, influencerBased: false, compliance: CLAIMS,
  },
  {
    key: "DG_RETARGETING", axis: "DIGITAL", family: "Retargeting",
    name: (c) => `${c.hero} Retargeting Boost`,
    concept: (c) => `Reciblage de 4 semaines des personnes ayant vu les vidéos, visité la page ou écrit sur WhatsApp : message preuve (avis, résultat cosmétique) puis offre en pharmacie pour ${c.product ?? "la gamme"}.`,
    objectives: { SELL_OUT: 0.9, ECOULEMENT: 0.8, FIDELISATION: 0.6 },
    targets: ["FEMMES_25_45", "JEUNES_18_25", "MAMANS", "FEMMES_45_PLUS", "HOMMES", "SPORTIFS"], productKinds: "ANY",
    channels: ["Meta Ads (reciblage)", "WhatsApp"],
    budget: { min: 3000, typical: 6000, max: 15000 },
    lines: [C("Diffusion Meta (reciblage)", "META", 0.8), C("Créations preuve et offre", "CREATION", 0.12), IMPREVUS()],
    reach: { contactLabel: "conversations / clics qualifiés", costPerContact: 8, trialRate: 0.35, conversionRate: 0.35, unitsPerBuyer: 1, usesAdsCost: true },
    steps: [S(-7, "Construire les audiences de reciblage"), S(-5, "Créations preuve et offre"), S(-3, "Valider les messages", "REGLEMENTAIRE"), S(0, "Lancement"), S(14, "Rafraîchir les créations si la fréquence dépasse 3"), S(28, "Bilan : coût par résultat, ventes relais")],
    contents: [{ format: "STORY", count: 2, title: "Créations reciblage", offset: -5 }],
    extraKpis: [{ label: "Fréquence maximale", value: () => "3,5" }],
    complexity: "LOW", prepDays: 7, durationDays: 28, cooldownDays: 45,
    execution: { kind: "CAMPAIGN", campaignType: "RETARGETING", channel: "META" },
    seasons: {}, cityBased: false, posBased: false, influencerBased: false,
  },
  {
    key: "DG_EDUCATION", axis: "DIGITAL", family: "Éducation produit",
    name: (c) => `${c.hero} Academy`,
    concept: (c) => `Série de 4 vidéos pédagogiques sponsorisées pendant 4 semaines : comment agit ${c.product ?? "la gamme"}, la bonne routine, les erreurs à éviter, les résultats cosmétiques à attendre. Les vidéos sont aussi envoyées aux pharmacies pour l'écran et le conseil.`,
    objectives: { NOTORIETE: 1, LANCEMENT: 0.8, ACQUISITION: 0.6, SELL_OUT: 0.5 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "JEUNES_18_25", "MAMANS", "HOMMES"], productKinds: "ANY",
    channels: ["Meta Ads", "Instagram", "Écrans pharmacies"],
    budget: { min: 6000, typical: 11000, max: 25000 },
    lines: [C("Production des 4 vidéos", "CREATION", 0.3), C("Tournage", "SHOOTING", 0.07), C("Diffusion Meta", "META", 0.55), IMPREVUS()],
    reach: { contactLabel: "vues qualifiées", costPerContact: 4, trialRate: 0.03, conversionRate: 0.3, unitsPerBuyer: 1 },
    steps: [S(-21, "Écrire les 4 scripts"), S(-14, "Valider les scripts", "REGLEMENTAIRE"), S(-10, "Tournage et montage"), S(-3, "Paramétrer la diffusion"), S(0, "Vidéo 1"), S(7, "Vidéo 2"), S(14, "Vidéo 3"), S(21, "Vidéo 4 et envoi aux pharmacies", "TRADE"), S(28, "Bilan : vues, coût par vue, recherches de pharmacies")],
    contents: [{ format: "VIDEO", count: 4, title: "Vidéos pédagogiques", offset: -7 }],
    extraKpis: [{ label: "Vidéos publiées", value: () => 4 }],
    complexity: "MEDIUM", prepDays: 21, durationDays: 28, cooldownDays: 90,
    execution: { kind: "CAMPAIGN", campaignType: "EDUCATION", channel: "META" },
    seasons: { rentree: 1 }, cityBased: false, posBased: false, influencerBased: false, compliance: CLAIMS,
  },
  {
    key: "DG_LEADGEN", axis: "DIGITAL", family: "Lead generation",
    name: (c) => `${c.hero} : échantillon offert`,
    concept: (c) => `Campagne Meta « recevez votre échantillon de ${c.product ?? "la gamme"} » : la personne laisse son contact (formulaire ou WhatsApp) et retire son échantillon dans une pharmacie partenaire, avec une offre de premier achat. Génère du trafic en officine et une base de contacts.`,
    objectives: { ACQUISITION: 1, LANCEMENT: 0.85, SELL_OUT: 0.8 },
    targets: ["FEMMES_25_45", "JEUNES_18_25", "MAMANS", "FEMMES_45_PLUS"], productKinds: "ANY",
    channels: ["Meta Ads (formulaire)", "WhatsApp", "Pharmacies de retrait"],
    budget: { min: 6000, typical: 12000, max: 30000 },
    lines: [C("Diffusion Meta (formulaire)", "META", 0.55), C("Échantillons", "ECHANTILLONS", 0.22), C("Créations", "CREATION", 0.08), C("Logistique vers les pharmacies", "TRADE", 0.07), IMPREVUS()],
    reach: { contactLabel: "contacts (leads)", costPerContact: 15, trialRate: 0.6, conversionRate: 0.25, unitsPerBuyer: 1, usesAdsCost: true },
    steps: [S(-21, "Choisir les pharmacies de retrait", "TRADE"), S(-18, "Commander les échantillons"), S(-14, "Formulaire, messages et créations"), S(-10, "Valider les messages", "REGLEMENTAIRE"), S(-5, "Livrer les échantillons aux pharmacies", "TRADE"), S(0, "Lancement"), S(7, "Relance WhatsApp des contacts non venus"), S(28, "Bilan : contacts, retraits, premiers achats")],
    contents: [{ format: "REEL", count: 1, title: "Échantillon offert", offset: -7 }, { format: "STORY", count: 2, title: "Où retirer son échantillon", offset: 0 }],
    extraKpis: [{ label: "Échantillons retirés", value: (b) => Math.round((b * 0.55) / 15 * 0.6) }],
    complexity: "MEDIUM", prepDays: 21, durationDays: 28, cooldownDays: 90,
    execution: { kind: "CAMPAIGN", campaignType: "ACQUISITION", channel: "META" },
    seasons: {}, cityBased: false, posBased: true, influencerBased: false,
  },
  {
    key: "DG_30DAY", axis: "DIGITAL", family: "30-Day Challenge",
    name: (c) => `${c.hero} 30-Day Challenge`,
    concept: (c) => `Défi de 30 jours sur Instagram : les participantes s'inscrivent, les 50 premières reçoivent ${c.product ?? "le produit"} via une pharmacie partenaire, partagent leur routine chaque semaine (stories), tirage final. Résultats cosmétiques constatés, jamais promis.`,
    objectives: { SELL_OUT: 0.9, FIDELISATION: 0.8, NOTORIETE: 0.85, LANCEMENT: 0.75 },
    targets: ["FEMMES_25_45", "JEUNES_18_25", "SPORTIFS", "MAMANS"], productKinds: ["DERMO", "COMPLEMENT"],
    channels: ["Instagram", "Meta Ads", "Micro-influence", "Pharmacies partenaires"],
    budget: { min: 12000, typical: 22000, max: 45000 },
    lines: [C("Diffusion Meta", "META", 0.35), C("Produits offerts", "ECHANTILLONS", 0.18), C("Contenus des participantes", "UGC", 0.12), C("Influenceuses relais", "INFLUENCE", 0.12), C("Lots du tirage", "GOODIES", 0.07), C("Créations", "CREATION", 0.08), IMPREVUS()],
    reach: { contactLabel: "participantes inscrites", costPerContact: 60, trialRate: 0.8, conversionRate: 0.3, unitsPerBuyer: 1.2 },
    steps: [S(-30, "Règlement du défi et mécanique"), S(-28, "Valider règlement et messages", "REGLEMENTAIRE"), S(-21, "Recruter 3 influenceuses relais"), S(-14, "Préparer les produits offerts avec les pharmacies", "TRADE"), S(-7, "Ouvrir les inscriptions"), S(0, "Début du défi"), S(7, "Point semaine 1 : stories des participantes"), S(14, "Point semaine 2"), S(21, "Point semaine 3"), S(30, "Clôture, tirage, bilan des ventes")],
    contents: [{ format: "REEL", count: 4, title: "Défi : semaines 1 à 4", offset: 0 }, { format: "STORY", count: 12, title: "Stories du défi", offset: 0 }],
    extraKpis: [{ label: "Participantes actives à J+30", value: (b) => Math.round(b / 60 * 0.5) }],
    complexity: "HIGH", prepDays: 30, durationDays: 30, cooldownDays: 180,
    execution: { kind: "CAMPAIGN", campaignType: "CAMPAGNE_360", channel: "META" },
    seasons: { rentree: 1, "solaire-haute": 1, ramadan: -1 }, cityBased: false, posBased: true, influencerBased: true, compliance: CLAIMS,
  },

  /* ================================ INFLUENCE ================================ */
  {
    key: "IN_SEEDING", axis: "INFLUENCE", family: "Seeding micro-influence",
    name: (c) => `${c.hero} Seeding Box`,
    concept: (c) => `Box ${c.brand} avec ${c.product ?? "la gamme"} envoyée à 15 à 25 micro-influenceuses (5 000 à 30 000 abonnés) proches de ${c.target.toLowerCase()} ; 5 d'entre elles sont rémunérées pour un réel et des stories, les autres publient librement.`,
    objectives: { LANCEMENT: 1, NOTORIETE: 0.9, ACQUISITION: 0.7, SELL_OUT: 0.5 },
    targets: ["FEMMES_25_45", "JEUNES_18_25", "MAMANS", "SPORTIFS", "FEMMES_45_PLUS"], productKinds: "ANY",
    channels: ["Instagram", "Micro-influence", "TikTok"],
    budget: { min: 5000, typical: 9000, max: 20000 },
    lines: [C("Rémunération de 5 influenceuses", "INFLUENCE", 0.4), C("Box et packaging", "GOODIES", 0.22), C("Produits de la box", "ECHANTILLONS", 0.18), C("Création de la box et du message", "CREATION", 0.12), IMPREVUS()],
    reach: { contactLabel: "personnes touchées", costPerContact: 2, trialRate: 0.02, conversionRate: 0.3, unitsPerBuyer: 1 },
    steps: [S(-14, "Sélectionner 15 à 25 profils (audience, engagement)"), S(-12, "Négocier les 5 collaborations rémunérées"), S(-10, "Créer et assembler les box"), S(-7, "Valider le brief de communication", "REGLEMENTAIRE"), S(-3, "Expédier les box"), S(0, "Début des publications"), S(7, "Relancer les influenceuses sans publication"), S(14, "Bilan : publications, portée, codes, ventes")],
    contents: [{ format: "STORY", count: 20, title: "Stories des influenceuses", offset: 3 }, { format: "REEL", count: 5, title: "Réels rémunérés", offset: 5 }],
    extraKpis: [{ label: "Influenceuses publiant", value: () => "≥ 12" }],
    complexity: "LOW", prepDays: 14, durationDays: 14, cooldownDays: 90,
    execution: { kind: "CAMPAIGN", campaignType: "INFLUENCE", channel: "INFLUENCE" },
    seasons: {}, cityBased: false, posBased: false, influencerBased: true,
  },
  {
    key: "IN_EXPERT", axis: "INFLUENCE", family: "Campagne experts",
    name: (c) => `Expert ${c.hero} Talks`,
    concept: (c) => `2 à 3 professionnels (dermatologue, nutritionniste, pharmacienne) expliquent ${c.product ?? "la gamme"} en live et en réels éducatifs, relayés en publicité. Le discours d'expert crédibilise le conseil en pharmacie.`,
    objectives: { NOTORIETE: 0.9, LANCEMENT: 0.85, SELL_OUT: 0.6, SELL_IN: 0.5 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "MAMANS", "PRESCRIPTEURS"], productKinds: "ANY",
    channels: ["Instagram (live)", "Meta Ads", "Experts"],
    budget: { min: 8000, typical: 15000, max: 30000 },
    lines: [C("Cachets des experts", "PRESCRIPTEURS", 0.45), C("Relais publicitaire", "META", 0.3), C("Montage et sous-titres", "CREATION", 0.17), IMPREVUS()],
    reach: { contactLabel: "vues qualifiées", costPerContact: 3, trialRate: 0.03, conversionRate: 0.3, unitsPerBuyer: 1 },
    steps: [S(-21, "Recruter les experts"), S(-14, "Préparer les questions et les supports"), S(-10, "Valider les messages", "REGLEMENTAIRE"), S(0, "Live expert"), S(3, "Publier les réels extraits"), S(5, "Relais publicitaire"), S(21, "Bilan : vues, questions, ventes relais")],
    contents: [{ format: "LIVE", count: 1, title: "Live expert", offset: 0 }, { format: "REEL", count: 3, title: "Extraits expert", offset: 3 }],
    extraKpis: [{ label: "Questions reçues en live", value: () => "≥ 30" }],
    complexity: "MEDIUM", prepDays: 21, durationDays: 21, cooldownDays: 120,
    execution: { kind: "CAMPAIGN", campaignType: "EDUCATION", channel: "INFLUENCE" },
    seasons: { rentree: 1 }, cityBased: false, posBased: false, influencerBased: false, compliance: CLAIMS,
  },
  {
    key: "IN_UGC_CREATORS", axis: "INFLUENCE", family: "Créatrices UGC",
    name: (c) => `${c.hero} Creator Lab`,
    concept: (c) => `6 créatrices UGC produisent 18 vidéos (routine, test, avis honnête) sur ${c.product ?? "la gamme"} avec droits d'usage 6 mois pour la publicité, Instagram et les écrans des pharmacies.`,
    objectives: { LANCEMENT: 0.8, SELL_OUT: 0.7, ACQUISITION: 0.7, NOTORIETE: 0.7 },
    targets: ["FEMMES_25_45", "JEUNES_18_25", "MAMANS", "FEMMES_45_PLUS"], productKinds: "ANY",
    channels: ["UGC", "Instagram", "Meta Ads", "Écrans pharmacies"],
    budget: { min: 6000, typical: 10000, max: 20000 },
    lines: [C("6 créatrices UGC (droits 6 mois)", "UGC", 0.7), C("Montage et déclinaisons", "CREATION", 0.12), C("Produits envoyés", "ECHANTILLONS", 0.1), IMPREVUS()],
    reach: { contactLabel: "vues", costPerContact: 5, trialRate: 0.03, conversionRate: 0.3, unitsPerBuyer: 1 },
    steps: [S(-14, "Brief et sélection des 6 créatrices"), S(-12, "Envoyer les produits"), S(-7, "Valider les scripts", "REGLEMENTAIRE"), S(0, "Réception des 18 vidéos"), S(3, "Montage des déclinaisons publicitaires"), S(7, "Envoi des vidéos aux pharmacies", "TRADE"), S(21, "Bilan : vidéos exploitées, performances")],
    contents: [{ format: "UGC", count: 18, title: "Vidéos UGC", offset: 0 }],
    extraKpis: [{ label: "Vidéos livrées", value: () => 18 }],
    complexity: "LOW", prepDays: 14, durationDays: 21, cooldownDays: 120,
    execution: { kind: "CAMPAIGN", campaignType: "INFLUENCE", channel: "INFLUENCE" },
    seasons: {}, cityBased: false, posBased: false, influencerBased: true, compliance: CLAIMS,
  },
  {
    key: "IN_AMBASSADOR", axis: "INFLUENCE", family: "Ambassadrice",
    name: (c) => `Ambassadrice ${c.hero}`,
    concept: (c) => `Partenariat de 3 mois avec une influenceuse au cœur de ${c.target.toLowerCase()} : 3 réels, 9 stories, présence à un événement de la marque et un code promo nominatif qui mesure le CA réellement attribué.`,
    objectives: { SELL_OUT: 0.9, NOTORIETE: 0.9, LANCEMENT: 0.8, FIDELISATION: 0.6 },
    targets: ["FEMMES_25_45", "JEUNES_18_25", "MAMANS", "SPORTIFS"], productKinds: "ANY",
    channels: ["Instagram", "TikTok", "Code promo", "Événement"],
    budget: { min: 12000, typical: 25000, max: 60000 },
    lines: [C("Cachet de l'ambassadrice (3 mois)", "INFLUENCE", 0.72), C("Produits", "ECHANTILLONS", 0.08), C("Créations et droits", "CREATION", 0.12), IMPREVUS()],
    reach: { contactLabel: "personnes touchées", costPerContact: 1.5, trialRate: 0.015, conversionRate: 0.35, unitsPerBuyer: 1 },
    steps: [S(-21, "Choisir l'ambassadrice (audience, valeurs, historique)"), S(-18, "Négocier le contrat et le code promo"), S(-14, "Valider le contrat", "DIRECTION"), S(-10, "Valider la charte de communication", "REGLEMENTAIRE"), S(0, "Annonce du partenariat"), S(30, "Point mois 1 : CA du code promo"), S(60, "Point mois 2"), S(90, "Bilan : CA attribué (code), portée, renouvellement")],
    contents: [{ format: "REEL", count: 3, title: "Réels de l'ambassadrice", offset: 0 }, { format: "STORY", count: 9, title: "Stories de l'ambassadrice", offset: 0 }],
    extraKpis: [{ label: "CA attribué (code promo nominatif)", value: () => "mesuré" }],
    complexity: "MEDIUM", prepDays: 21, durationDays: 90, cooldownDays: 180,
    execution: { kind: "CAMPAIGN", campaignType: "INFLUENCE", channel: "INFLUENCE" },
    seasons: {}, cityBased: false, posBased: false, influencerBased: true, compliance: CLAIMS,
  },

  /* ================================ CONTENU ================================ */
  {
    key: "CT_EDUCATION", axis: "CONTENU", family: "Série pédagogique",
    name: (c) => `${c.hero} expliqué`,
    concept: (c) => `Série de 6 publications sur 6 semaines (3 carrousels, 3 réels) : les actifs de ${c.product ?? "la gamme"}, la routine, les idées reçues, le conseil du pharmacien. Un visuel écran est fourni aux pharmacies.`,
    objectives: { NOTORIETE: 0.9, LANCEMENT: 0.8, SELL_OUT: 0.5, FIDELISATION: 0.5 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "JEUNES_18_25", "MAMANS", "HOMMES"], productKinds: "ANY",
    channels: ["Instagram", "Facebook", "Écrans pharmacies"],
    budget: { min: 3000, typical: 6000, max: 12000 },
    lines: [C("Création graphique et rédaction", "CREATION", 0.5), C("Tournage des réels", "SHOOTING", 0.22), C("Boost des publications", "META", 0.2), IMPREVUS()],
    reach: { contactLabel: "vues qualifiées", costPerContact: 3, trialRate: 0.02, conversionRate: 0.3, unitsPerBuyer: 1 },
    steps: [S(-14, "Plan éditorial des 6 publications"), S(-10, "Production"), S(-7, "Valider les messages", "REGLEMENTAIRE"), S(0, "Publication 1"), S(21, "Publication 4 et visuel écran aux pharmacies", "TRADE"), S(42, "Bilan : portée, enregistrements, questions")],
    contents: [{ format: "CARROUSEL", count: 3, title: "Carrousels pédagogiques", offset: 0 }, { format: "REEL", count: 3, title: "Réels pédagogiques", offset: 7 }, { format: "VISUEL_PHARMACIE", count: 1, title: "Visuel écran pharmacie", offset: 21 }],
    extraKpis: [{ label: "Enregistrements des carrousels", value: () => "≥ 3 % de la portée" }],
    complexity: "LOW", prepDays: 14, durationDays: 42, cooldownDays: 90,
    execution: { kind: "CAMPAIGN", campaignType: "EDUCATION", channel: "META" },
    seasons: { rentree: 1 }, cityBased: false, posBased: false, influencerBased: false, compliance: CLAIMS,
  },
  {
    key: "CT_BEFORE_AFTER", axis: "CONTENU", family: "Avant / après",
    name: (c) => `Avant / après ${c.hero}`,
    concept: (c) => `5 utilisatrices suivies 4 semaines avec ${c.product ?? "la gamme"} : photos et vidéos datées dans les mêmes conditions, résultats cosmétiques constatés et mention « résultats individuels ». Diffusion organique et publicitaire.`,
    objectives: { SELL_OUT: 0.8, NOTORIETE: 0.7, ECOULEMENT: 0.5, LANCEMENT: 0.6 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "JEUNES_18_25"], productKinds: DERMO_ONLY,
    channels: ["Instagram", "Meta Ads"],
    budget: { min: 5000, typical: 9000, max: 18000 },
    lines: [C("Rémunération des utilisatrices", "UGC", 0.35), C("Shooting (J0 et J28)", "SHOOTING", 0.25), C("Produits", "ECHANTILLONS", 0.08), C("Montage", "CREATION", 0.14), C("Boost", "META", 0.1), IMPREVUS()],
    reach: { contactLabel: "vues qualifiées", costPerContact: 3, trialRate: 0.03, conversionRate: 0.3, unitsPerBuyer: 1 },
    steps: [S(-35, "Recruter 5 utilisatrices (consentement écrit)"), S(-32, "Shooting J0 (conditions standardisées)"), S(-4, "Shooting J28"), S(-3, "Valider les messages et mentions", "REGLEMENTAIRE"), S(0, "Publication"), S(14, "Bilan : portée, commentaires, ventes relais")],
    contents: [{ format: "CARROUSEL", count: 1, title: "Avant / après", offset: 0 }, { format: "REEL", count: 2, title: "Témoignages avant / après", offset: 3 }],
    extraKpis: [{ label: "Utilisatrices suivies", value: () => 5 }],
    complexity: "MEDIUM", prepDays: 35, durationDays: 14, cooldownDays: 180,
    execution: { kind: "CAMPAIGN", campaignType: "CONVERSION", channel: "META" },
    seasons: {}, cityBased: false, posBased: false, influencerBased: false,
    compliance: "Avant / après : résultats cosmétiques constatés uniquement, photos non retouchées, mention « résultats individuels », validation réglementaire obligatoire.",
  },
  {
    key: "CT_EXPERT_SERIES", axis: "CONTENU", family: "Contenus d'expert",
    name: (c) => `L'avis de l'expert sur ${c.hero}`,
    concept: (c) => `4 vidéos courtes d'une pharmacienne ou d'un dermatologue répondant aux vraies questions sur ${c.product ?? "la gamme"}, publiées et transmises aux pharmacies partenaires pour leurs propres réseaux.`,
    objectives: { NOTORIETE: 0.9, LANCEMENT: 0.8, SELL_IN: 0.5, SELL_OUT: 0.5 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "MAMANS", "PHARMACIENS"], productKinds: "ANY",
    channels: ["Instagram", "Pharmacies partenaires", "WhatsApp"],
    budget: { min: 5000, typical: 9000, max: 18000 },
    lines: [C("Cachet de l'expert", "PRESCRIPTEURS", 0.4), C("Tournage", "SHOOTING", 0.25), C("Montage", "CREATION", 0.17), C("Boost", "META", 0.1), IMPREVUS()],
    reach: { contactLabel: "vues qualifiées", costPerContact: 3, trialRate: 0.02, conversionRate: 0.3, unitsPerBuyer: 1 },
    steps: [S(-21, "Recruter l'expert"), S(-14, "Recueillir les questions (WhatsApp, commentaires, pharmacies)", "TRADE"), S(-10, "Tournage des 4 vidéos"), S(-5, "Valider les vidéos", "REGLEMENTAIRE"), S(0, "Publication vidéo 1"), S(21, "Vidéo 4 et kit aux pharmacies", "TRADE"), S(28, "Bilan : vues, partages par les pharmacies")],
    contents: [{ format: "VIDEO", count: 4, title: "Vidéos d'expert", offset: 0 }],
    extraKpis: [{ label: "Pharmacies relayant les vidéos", value: () => "≥ 5" }],
    complexity: "MEDIUM", prepDays: 21, durationDays: 28, cooldownDays: 120,
    execution: { kind: "CAMPAIGN", campaignType: "EDUCATION", channel: "META" },
    seasons: {}, cityBased: false, posBased: true, influencerBased: false, compliance: CLAIMS,
  },
  {
    key: "CT_FAQ", axis: "CONTENU", family: "Série FAQ",
    name: (c) => `${c.hero} : vos questions`,
    concept: (c) => `Série FAQ construite sur les questions réellement posées (WhatsApp, commentaires, comptoirs) sur ${c.product ?? "la gamme"} : 8 stories à la une et 2 réels de réponses courtes.`,
    objectives: { FIDELISATION: 0.75, NOTORIETE: 0.7, SELL_OUT: 0.6, LANCEMENT: 0.6 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "JEUNES_18_25", "MAMANS", "HOMMES", "SPORTIFS"], productKinds: "ANY",
    channels: ["Instagram (stories à la une)", "WhatsApp"],
    budget: { min: 1500, typical: 3500, max: 8000 },
    lines: [C("Création graphique et rédaction", "CREATION", 0.62), C("Boost des réels", "META", 0.3), IMPREVUS()],
    reach: { contactLabel: "vues", costPerContact: 2.5, trialRate: 0.02, conversionRate: 0.3, unitsPerBuyer: 1 },
    steps: [S(-7, "Recueillir les 10 questions les plus fréquentes", "TRADE"), S(-5, "Rédiger les réponses"), S(-3, "Valider les réponses", "REGLEMENTAIRE"), S(0, "Publication des stories à la une et du réel 1"), S(7, "Réel 2"), S(21, "Bilan : vues, messages reçus")],
    contents: [{ format: "STORY", count: 8, title: "FAQ à la une", offset: 0 }, { format: "REEL", count: 2, title: "Réponses en vidéo", offset: 0 }],
    extraKpis: [],
    complexity: "LOW", prepDays: 7, durationDays: 21, cooldownDays: 60,
    execution: { kind: "CAMPAIGN", campaignType: "EDUCATION", channel: "META" },
    seasons: {}, cityBased: false, posBased: false, influencerBased: false, compliance: CLAIMS,
  },
  {
    key: "CT_TESTIMONIALS", axis: "CONTENU", family: "Témoignages",
    name: (c) => `Elles ont adopté ${c.hero}`,
    concept: (c) => `6 témoignages vidéo de clientes réelles de ${c.product ?? "la gamme"}, recrutées en pharmacie partenaire (accord écrit), publiés sur 3 semaines et boostés vers ${c.target.toLowerCase()}.`,
    objectives: { SELL_OUT: 0.8, FIDELISATION: 0.75, NOTORIETE: 0.7, ACQUISITION: 0.6 },
    targets: ["FEMMES_25_45", "FEMMES_45_PLUS", "MAMANS", "JEUNES_18_25"], productKinds: "ANY",
    channels: ["Instagram", "Meta Ads", "Pharmacies partenaires"],
    budget: { min: 3000, typical: 7000, max: 15000 },
    lines: [C("Témoignages (6 clientes)", "UGC", 0.4), C("Tournage", "SHOOTING", 0.2), C("Boost", "META", 0.24), C("Remerciements", "GOODIES", 0.08), IMPREVUS()],
    reach: { contactLabel: "vues qualifiées", costPerContact: 3, trialRate: 0.03, conversionRate: 0.3, unitsPerBuyer: 1 },
    steps: [S(-21, "Recruter 6 clientes avec les pharmacies (accord écrit)", "TRADE"), S(-14, "Tournage"), S(-7, "Valider les messages", "REGLEMENTAIRE"), S(0, "Publication du témoignage 1"), S(14, "Publication des témoignages 5 et 6"), S(21, "Bilan : vues, commentaires, ventes relais")],
    contents: [{ format: "UGC", count: 6, title: "Témoignages clientes", offset: 0 }],
    extraKpis: [{ label: "Témoignages publiés", value: () => 6 }],
    complexity: "LOW", prepDays: 21, durationDays: 21, cooldownDays: 120,
    execution: { kind: "CAMPAIGN", campaignType: "CONVERSION", channel: "META" },
    seasons: {}, cityBased: false, posBased: true, influencerBased: false, compliance: CLAIMS,
  },
];

export const TEMPLATE_BY_KEY = new Map(TEMPLATES.map((t) => [t.key, t]));
